name: Full CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Backend
        run: docker build -t fpv-backend ./backend
      - name: Build Frontend
        run: docker build -t fpv-frontend ./frontend
      - name: Run Tests
        run: |
          cd backend && python -m pytest